services:
  library-postgres:
    image: postgres:15
    container_name: library-postgres
    restart: always
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - library_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d librarydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  customer:
    build: ./customers
    container_name: customer
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: library-postgres
      DB_PORT: 5432
      DB_USER: library_user
      DB_PASS: library_pass
      DB_NAME: librarydb
    depends_on:
      library-postgres:
        condition: service_healthy

  order:
    build: ./orders
    container_name: order
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: library-postgres
      DB_PORT: 5432
      DB_USER: library_user
      DB_PASS: library_pass
      DB_NAME: librarydb
    depends_on:
      library-postgres:
        condition: service_healthy

  book:
    build: ./books
    container_name: book
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_HOST: library-postgres
      DB_PORT: 5432
      DB_USER: library_user
      DB_PASS: library_pass
      DB_NAME: librarydb
    depends_on:
      library-postgres:
        condition: service_healthy

volumes:
  library_postgres_data:
