apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: orders
          image: ghcr.io/narendra-singh-bacancy/library-management-system-order:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: orders-config

