apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30021  # Choose a port between 30000–32767
